import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./component/SessionWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "learn Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* since we have declared SessionWrapper as client component, are all the wrapped child also client side now? */}
      <SessionWrapper>
        <body className={inter.className}>{children}</body>
      </SessionWrapper>
    </html>
  );
}
